// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAisQRvry56Hl2FsD1pFckz5xdxQV5FIwc',
    appId: '1:305799257185:web:45e4c64bffe8e6e9465e20',
    messagingSenderId: '305799257185',
    projectId: 'makeyourmeal-757bd',
    authDomain: 'makeyourmeal-757bd.firebaseapp.com',
    storageBucket: 'makeyourmeal-757bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuOkpT-liTnhKtTEj9BMml6c1982n6Ppg',
    appId: '1:305799257185:android:1304c7bd5280bd46465e20',
    messagingSenderId: '305799257185',
    projectId: 'makeyourmeal-757bd',
    storageBucket: 'makeyourmeal-757bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChRrtNM1gwKe3AhClsP3JbMR3jPZkrmhk',
    appId: '1:305799257185:ios:0343b7a4a2ca82fe465e20',
    messagingSenderId: '305799257185',
    projectId: 'makeyourmeal-757bd',
    storageBucket: 'makeyourmeal-757bd.firebasestorage.app',
    iosBundleId: 'com.example.makeYourMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChRrtNM1gwKe3AhClsP3JbMR3jPZkrmhk',
    appId: '1:305799257185:ios:0343b7a4a2ca82fe465e20',
    messagingSenderId: '305799257185',
    projectId: 'makeyourmeal-757bd',
    storageBucket: 'makeyourmeal-757bd.firebasestorage.app',
    iosBundleId: 'com.example.makeYourMeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAisQRvry56Hl2FsD1pFckz5xdxQV5FIwc',
    appId: '1:305799257185:web:1cc61449f676d145465e20',
    messagingSenderId: '305799257185',
    projectId: 'makeyourmeal-757bd',
    authDomain: 'makeyourmeal-757bd.firebaseapp.com',
    storageBucket: 'makeyourmeal-757bd.firebasestorage.app',
  );
}
